### ISSUE TITLE
量化

### ISSUE THREAD

**Issue by Liqing6668** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#1]
您好，我现在模型大小通过剪枝已经剪到了原来模型10%，请问量化效果还大吗？

**Comment by SpursLipu** [comment]
量化我还在更新中，现在只做了w的二值化，具体效果可能和数据集还有关，你可以试试逐层量化，看看量化多少层精度还不变，这样能够最小化模型且保证精度，如果全部量化的话，感觉精度会掉不少。

**Comment by 18483666678** [comment]
我在coldlarry/YOLOv3-complete-pruning项目中训练自定义数据集，测试的mAP在0.796，但是在检测的时候出现少框或者多框的情况，是我数据处理的问题，还是我什么参数没调对吗？

**Comment by SpursLipu** [comment]
你可以试着改变一下置信度度和iou的阈值，多框可能是iou的阈值太小，少框可能是置信度的阈值太大，你调着试试吧

**Comment by H-YunHui** [comment]
@SpursLipu 
![微信图片_20200425135335](https://user-images.githubusercontent.com/44078888/80272635-cd73fd00-86fd-11ea-9df0-16baf502e595.png)
作者是否在此模型基础上使用过BNN、BWN和stage-wise 训练策略训练策略，精度和速度如何？
