### ISSUE TITLE
some question about the yolov3tiny-mobilenet-small-coco?

### ISSUE THREAD

**Issue by H-YunHui** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#11]
1.在MobileNetV3中，原作者在bneck中并未使用relu6和linear，relu6和linear是作者在V2中使用的，在V3中使用ReLU和h-swish
2.yolov3tiny-mobilenet-small-coco.cfg中每一个深度卷积和逐点卷积后都有激活函数，这个是如何得出的，在论文中并未看到这样的操作？

**Comment by SpursLipu** [comment]
感谢指出问题，我在设计的时候也是参照mobilenetv2的结构，没有考虑这么多，我再做些实验试试。

**Comment by SpursLipu** [comment]
我用做了些实验，调整结构后得到了差不多的结果。原作中并没有使用relu6，linear在具体实现是是指不适用激活函数，原作在逐点卷积后也没有使用激活函数。
