### ISSUE TITLE
其他检测模型是否通用例如ssd yolo4 ?

### ISSUE THREAD

**Issue by sky186** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#14]
@SpursLipu 
其他检测模型是否通用例如ssd yolo4 ?还是有很多需要注意的的点需要自己修改
分类和检测的模型压缩有什么区别吗？现在发布的论文都是验证的分类模型，不可以都通用吗?

**Comment by sky186** [comment]
@sky186 
您觉得，哪个方法比较通用，精度损失很少的，压缩方式

**Comment by SpursLipu** [comment]
YOLOv4已经更新，之后应该还会更新SSD，压缩方法的话各有优劣.....这个不太好说
