### ISSUE TITLE
請問目前的yolov3 mobilenetv3 有錯誤嗎?

### ISSUE THREAD

**Issue by www7890** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#17]
首先謝謝這份實作!
想請教你在實驗記錄裡提到你發現模型結構有錯，目前已經在最新的repo版本中修正了嗎?

**Comment by SpursLipu** [comment]
只是之前在网上看mobilenetv3时发现有不同的结构实现，经过测试以后感觉效果相差不多。

**Comment by www7890** [comment]
謝謝回覆!
期待pretrain 的 mobilenetv3+yolov3 weights!
