### ISSUE TITLE
kmeans anchors

### ISSUE THREAD

**Issue by SISTMrL** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#20]
when I use the anchor box clustered from my own data, why map is decreased? use the source code's anchors size, my best map is 0.95, but when I use the anchor size for my own data, the best map just is nearly 0.7

**Comment by SpursLipu** [comment]
I think it depend on distribution of your dataset. If it is concentrated in a small range, clustering will be necessary. But it's just my empirical thought, you can select best way by trying.

**Comment by SISTMrL** [comment]
Yes，the region I need to detect is small relative to the whole and adjacent to each other, so i do the kmeans anchors




| |
刘志超
|
|
邮箱：15256956711@163.com
|

签名由 网易邮箱大师 定制

On 05/29/2020 20:02, SpursLipu wrote:

I think it depend on distribution of your dataset. If it is concentrated in a small range, clustering will be necessary. But it's just my empirical thought, you can select best way by trying.
