### ISSUE TITLE
prune

### ISSUE THREAD

**Issue by SISTMrL** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#28]
你好，能不能在readme中贴出prune的参考论文链接，小白第一次接触压缩，不知道code中的剪枝是对应哪些论文。还有在进行剪枝稀疏化训练时我查看了代码好像并没有生成新的cfg文件，请问还是使用原来的yolov3.cfg文件吗？还有i请问下，你在训练时percent的参数一般给的是多少，希望能做下参考，十分感谢

**Comment by SpursLipu** [comment]
network slimming你搜这个就行了

**Comment by chumingqian** [comment]
@SISTMrL > 你好，能不能在readme中贴出prune的参考论文链接，小白第一次接触压缩，不知道code中的剪枝是对应哪些论文。还有在进行剪枝稀疏化训练时我查看了代码好像并没有生成新的cfg文件，请问还是使用原来的yolov3.cfg文件吗？还有i请问下，你在训练时percent的参数一般给的是多少，希望能做下参考，十分感谢

 你好， 我使用稀疏化训练， --prune 0为正常剪枝和规整剪枝的稀疏化 ； 这一步 我也没有生成新的 cfg 文件，请问 是哪里的原因？
