### ISSUE TITLE
quantization

### ISSUE THREAD

**Issue by SISTMrL** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#29]
你好，就之前我提问的为何量化后模型大小没有发生变化，你回答说是实际部署才会变小， 请问下该如何进行实际部署，临近期末课程课题的deadline, 诚盼回复，十分感谢！

**Comment by SpursLipu** [comment]
这个得看你的部署平台.....你用什么平台部署？

**Comment by SISTMrL** [comment]
你好，原来是这样子的，那我暂时先不考虑量化了，先把期末课程的课题应付完再来请教，十分感谢！

**Comment by SISTMrL** [comment]
请问下剪枝也是需要考虑到实际的部署平台吗

**Comment by SpursLipu** [comment]
剪植不用啊，你跑一下剪植的程序，会生成新的cfg文件和weights文件

**Comment by SISTMrL** [comment]
谢谢，正在跑，遇到一个bug，自己正在尝试解决，解决不了再来请教，十分感谢🙏




| |
刘志超
|
|
邮箱：15256956711@163.com
|

签名由 网易邮箱大师 定制

On 06/06/2020 19:51, SpursLipu wrote:

剪植不用啊，你跑一下剪植的程序，会生成新的cfg文件和weights文件
