### ISSUE TITLE
yolov3的8位量化实验

### ISSUE THREAD

**Issue by Blue-Eagle-10** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#3]
@SpursLipu ，

您好！感谢您的分享，受益匪浅！请问，您有做过yolov3的8位量化实验么？谢谢！

祝好！

**Comment by SpursLipu** [comment]
您好！ https://github.com/coldlarry/YOLOv3-complete-pruning 这是我学长的仓库，里面有基于DoReFa方法的定点量化，你可以参考。

**Comment by Blue-Eagle-10** [comment]
@SpursLipu ，

您好！非常感谢，您给的您学长的代码已经调试好，能运行了，谢谢您的分享！
