### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by SISTMrL** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#31]
imgsz_min, imgsz_max, imgsz_test = opt.img_size  # img sizes (min, max, test)
gs = 64 
assert math.fmod(imgsz_min, gs) == 0, '--img-size %g must be a %g-multiple' % (imgsz_min, gs)
你好，今天下午运行你最新版的程序时，我的img_size为608，所以我的imgsz_min也是608，因此出错了，所以不是很理解为何要有这个assert语句，grid size我理解应该是三个yololayer输出的feature map的尺寸，为何这里grid size直接设置为64了

**Comment by SpursLipu** [comment]
这个是新u版yolo的一个更新，我也没有理解具体的原因，可能是multi-scale训练时需要保持各种img_size的输出精度都较高参用的一种策略吧。如果设置成gs=32就可以使用608输入训练了
