### ISSUE TITLE
prune后map下降幅度非常大

### ISSUE THREAD

**Issue by SISTMrL** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#32]
剪枝后，map从0.84->0.035,为何下降如此的低， prune ratio是0.2， --percent参数是0.2，诚盼回复，十分感谢

**Comment by SpursLipu** [comment]
剪植后需要finetuning，就是以剪植后的模型权重为预训练权重重新训练剪植后的模型

**Comment by SpursLipu** [comment]
剪植确实存在bug，是我更新代码之后留下的问题，有可能使用稀疏化指令的时候没有进行稀疏化，我再调整一下。
