### ISSUE TITLE
为什么每次训练都需要预训练权重，如果不指定预训练权重，是否可以从头开始训练自己的数据集？十分感谢您的回答！

### ISSUE THREAD

**Issue by songzhonghao** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#34]

**Comment by SpursLipu** [comment]
确实可以从头训练但是相比预训练从头训练一般有两个问题个问题
1、训练速度很慢。
2、如果没有梯度稳定的机制从头训练无法达到与训练的精度。
你可以参照一下何凯明发过的一篇文章，主要是讲预训练和直接训练的区别的。
论文：Rethinking ImageNet Pre-training
