### ISSUE TITLE
关于俯视图车辆检测

### ISSUE THREAD

**Issue by pch9520** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#35]
你好，用了你的Dior数据集的权重文件，在检测的时候俯视图的车辆检测效果并不好，跟你README.md上的显示效果不一样，我用一张截图测试了一下，放在下面链接上:
链接: https://pan.baidu.com/s/1AYaojpyz8btcHpQ7MngXTg 提取码: n5hf

**Comment by SpursLipu** [comment]
这个是数据集的问题，dior主要是卫星遥感图片，你可以试试用visdrone训练出的权重文件。

**Comment by pch9520** [comment]
我用visdrone的权重也试过，不行的。对于Dior训练出来的权重，我把Dior数据集中的卫星遥感图片喂进去测试出来效果也是很差的，都检测到frisbee去了，没有检测出车辆

**Comment by SpursLipu** [comment]
你看看imgsize对不对我训练的都是应该用的都是608的。

**Comment by SpursLipu** [comment]
我md上放的就是dior测试集的图片，权重应该没问题，你看看你的设置

**Comment by pch9520** [comment]
我是下载了你的.weights文件以后在darknet上测试的，识别不了，是不是转换成.weights文件的过程中出错了

**Comment by SpursLipu** [comment]
转化应该没有问题...在我的仓库是可以测试的，你用了我的cfg文件了吗？

**Comment by SpursLipu** [comment]
yolov3.cfg与我仓库里面使用的yolov3-visdrone.cfg文件是不同的，类别设置，anchor不一样

**Comment by pch9520** [comment]
好的，我了解了，我明天试试，dior的weights对应yolov3-onDIOR.cfg，visdrone的weights对应yolov3-visdrone.cfg对嘛？

**Comment by pch9520** [comment]
我试了一下，可以用了，但是在我们自己的视频上检测率不是很高，我们应该还要继续训练

**Comment by SpursLipu** [comment]
如果是你们自己的数据集，还是再训练下比较好
