### ISSUE TITLE
你好，可以分享一下Yolo训练BDD100K的权重文件吗，百度云链接失效了

### ISSUE THREAD

**Issue by Sadudu** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#4]
你好，可以分享一下Yolo训练BDD100K的权重文件吗，百度云链接失效了

**Comment by SpursLipu** [comment]
好

**Comment by SpursLipu** [comment]
弄好了 你再试一下

**Comment by Sadudu** [comment]
好的，非常感谢大佬！！！可以加个联系方式吗，我最近也在用Yolo 训练BDD100K，遇到了一些问题，不知能否与大佬交流一下。

**Comment by SpursLipu** [comment]
有啥就在这个交流吧，还挺方便的，我会尽快回复的

**Comment by Sadudu** [comment]
大佬训练BDD100K数据集的时候有没有遇到过loss下降不下来的问题，我试了Yolo v3的原版，loss下降到8-10就不再下降了。  现在在用CornerNet-lite训练，loss在3左右，也是下降不下去。

**Comment by SpursLipu** [comment]
是用我的仓库吗？我的仓库会loss会一直掉。但是感觉还是要看map吧
