### ISSUE TITLE
请问一下你的YOLOv3 + mobilenetv3的准确率有多少呀，在voc数据上试过吗

### ISSUE THREAD

**Issue by chengyequn** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#7]

**Comment by SpursLipu** [comment]
没在voc上做，最近还在训coco 还没有训好

**Comment by H-YunHui** [comment]
@SpursLipu 
请问下YOLOv3tiny-mobilenet-small FPS能达到多少？

**Comment by H-YunHui** [comment]
@SpursLip
还想请问下，yolov3tiny-mobilenet-small-coco.cfg配置文件是根据哪个版本的MobileNetV3代码更改的，可否提供下链接？

**Comment by SpursLipu** [comment]
是原论文提供的，具体你可以参照mobilenet原论文

**Comment by SpursLipu** [comment]
FPS的话会比tiny-yolo慢一些，具体还要看设备

**Comment by H-YunHui** [comment]
@SpursLipu 
![微信图片_20200418213327](https://user-images.githubusercontent.com/44078888/79639195-c8262800-81bc-11ea-817d-18295ff80a35.png)
yolov3tiny-mobilenet-small参数量比yolov3tiny小很多，速度会慢吗？能否提供下你的设备以及在你设备上yolov3tiny-mobilenet-small和yolov3tiny分别取得的FPS，谢谢

**Comment by SpursLipu** [comment]
我在1050ti上测过，只不过用的是别的数据集，tiny28.57fps，mobilenet-small25.64fps。推理速度不光和参数量有关，mobilenet的模型结构相对复杂层数也多一些，速度就会慢一些。

**Comment by H-YunHui** [comment]
@SpursLipu 
你测试时使用图片测试还是rtsp视频流测试？

**Comment by SpursLipu** [comment]
有点给忘了，好像是在测试集上跑的数据，但是tiny会快一些这个应该没问题。

**Comment by H-YunHui** [comment]
好的，谢谢回复

**Comment by SpursLipu** [comment]
没事
