### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by SISTMrL** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#8]
你好，请问下如何制作并训练自己的数据集呢？本人期末project是做X图片里的检测，同时也想学习模型压缩的知识，十分感谢

**Comment by SpursLipu** [comment]
你的图片有标注好label吗？如果已经标注好了，按照我提供的数据集那种格式转化就可以了

**Comment by SISTMrL** [comment]
> 你的图片有标注好label吗？如果已经标注好了，按照我提供的数据集那种格式转化就可以了
你好，我现在想跑COCO数据集，但是我遇到个问题：no file in ./data/coco/train2017.txt，请问下这个txt是怎么得到的，我看COCO官网并没有，对你的数据集的格式不是很了解，求告知，谢谢！

**Comment by SpursLipu** [comment]
这个你可以在我分享的百度云文件里面下载到。
