### ISSUE TITLE
MobileNetV3 Detection

### ISSUE THREAD

**Issue by H-YunHui** [SpursLipu/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone#9]
在检测部分你使用的是完整的MobileNet-Large和MobileNet-Small，而作者在原文"6.3. Detection"部分做了一些对比试验，提出了两个层C4和C5，第一个层C4，在Large里对应第13个bneck，在Small里对应第9个bneck，C5均对应pooling前的那一层，操作如下“We additionally reduce the channel counts of all feature layers between C4 and C5 by 2”，在COCO结果如下：
![微信图片_20200421135814](https://user-images.githubusercontent.com/44078888/79830642-722dcc00-83d8-11ea-9072-e083e5f374e1.png)
请问下，你按照这个操作试过没，真的能够保持精度不变的情况下提速吗？

**Comment by H-YunHui** [comment]
在SE Model论文中，作者通过实验得出，当reduction=16，精度和复杂度之间取得了很好的平衡，而你的SE模块中，reduction设置为当前bneck的输出通道数（out），这样设置的原因是什么呢？实验得出的吗？

**Comment by SpursLipu** [comment]
第一个问题：我确实没有试，后续可以测试一下效果。
第二个问题：我也是参照网上的mobilenet的实现他们的代码采用的是reduction=4的实现，我也没有理解这个设计，也许是在网络结构搜索时搜索的最佳效果吧。

**Comment by H-YunHui** [comment]
@SpursLipu 
感谢回复
